import { useState } from 'react';
import { Link, NavLink, useParams, useSearchParams } from 'react-router-dom';
import { Download, Plus, ShieldCheck } from 'lucide-react';
import { useAdmin } from '../app/context';
import { can, label, ROLES } from '../lib/model';
import { aggregateCSV, auditVisible, entityPath, metrics } from '../lib/reporting';
import { BackLink, Badge, Button, ButtonLink, DateText, DecisionDialog, Descriptions, Empty, Field, Note, PageHeader, Panel, Register } from '../components/ui';
import EditDialog from '../components/ui/EditDialog';

export function Analytics() {
  const { data } = useAdmin(); const [params, setParams] = useSearchParams();
  const today = new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Dhaka' });
  const filters = { from: params.get('from') || today.slice(0, 7) + '-01', to: params.get('to') || today, department: params.get('department') || '' };
  const invalid = filters.from > filters.to;
  const rows = invalid ? [] : metrics(data, filters);
  const set = (key, value) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next); };
  const download = () => { const link = document.createElement('a'); const url = URL.createObjectURL(new Blob(['\uFEFF' + aggregateCSV(rows, filters)], { type: 'text/csv;charset=utf-8' })); link.href = url; link.download = `ugrads-aggregates-${filters.from}-${filters.to}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <><PageHeader title="Analytics" description="Defined measures from the records in this workspace." actions={<Button disabled={invalid} onClick={download}><Download size={16} />Export aggregates</Button>} /><Panel><div className="analytics-filters"><Field label="From · Dhaka">{p => <input {...p} type="date" value={filters.from} onChange={e => set('from', e.target.value)} />}</Field><Field label="To · Dhaka">{p => <input {...p} type="date" value={filters.to} onChange={e => set('to', e.target.value)} />}</Field><Field label="Department">{p => <select {...p} value={filters.department} onChange={e => set('department', e.target.value)}><option value="">All departments</option>{data.departments.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select>}</Field></div></Panel>{invalid ? <Note tone="warning">The end date must be on or after the start date.</Note> : <div className="analytics-grid">{rows.map(r => <Panel key={r.name}><div className="panel-body"><h2>{r.name}</h2><div className="analytics-value">{r.value}</div><p className="muted">{r.definition}</p></div></Panel>)}</div>}<Note>Counts include prototype fixtures and local decisions. Current snapshots are explicitly marked. Reach, clicks, delivered notifications and attendance have no connected data source.</Note></>;
}
export function Audit({ detail = false }) {
  const { data, actor } = useAdmin(); const { id } = useParams(); const [params, setParams] = useSearchParams();
  const permitted = data.audit.filter(e => auditVisible(e, actor, data));
  if (detail) {
    const row = permitted.find(e => e.id === id);
    if (!row) return <Empty level={1} title="Audit entry unavailable" description="This entry is missing or outside your audit scope." action={<ButtonLink to="/audit">Back to audit</ButtonLink>} />;
    const exists = data[row.collection]?.some(r => r.id === row.entityId);
    return <><BackLink to="/audit" /><PageHeader title={`${label(row.action)} · ${row.subject}`} description="Recorded local decision. Audit entries cannot be edited in this interface." /><Panel title="Decision record"><Descriptions items={[["Timestamp · Dhaka", <DateText value={row.at} full />], ['Actor', `${row.actorName} · ${ROLES[row.actorRole]} · ${row.actorId}`], ['Module', row.collection], ['Subject ID', row.entityId], ['Result', 'Committed'], ['Reason', row.reason || 'No reason required'], ['Revision', row.revision], ['Before', row.before ? `Status: ${row.before.status || '—'}; revision: ${row.before.revision}; owner: ${row.before.ownerId || '—'}` : 'New record'], ['After', `Status: ${row.after.status || '—'}; revision: ${row.after.revision}; owner: ${row.after.ownerId || '—'}`], ['Changed fields', row.changedFields?.join(', ') || '—']]} /><div className="panel-body">{exists ? <ButtonLink to={entityPath(row)}>Open subject</ButtonLink> : <Note>The original record is unavailable.</Note>}</div></Panel></>;
  }
  const rows = permitted.filter(e => (!params.get('from') || Date.parse(e.at) >= Date.parse(`${params.get('from')}T00:00:00+06:00`)) && (!params.get('to') || Date.parse(e.at) <= Date.parse(`${params.get('to')}T23:59:59+06:00`)));
  return <><PageHeader title="Audit log" description="Who changed what, when, and why. Your role determines which records appear." /><Note>This local prototype log records committed actions. It is not a tamper-proof production ledger.</Note><Panel><div className="analytics-filters">{['from', 'to'].map(key => <Field key={key} label={`${key === 'from' ? 'From' : 'To'} · Dhaka`}>{p => <input {...p} type="date" value={params.get(key) || ''} onChange={e => { const n = new URLSearchParams(params); n.set(key, e.target.value); n.delete('page'); setParams(n); }} />}</Field>)}</div><Register rows={rows} defaultSort="-at" searchLabel="Search subject, reason or ID" searchText={r => `${r.subject} ${r.entityId} ${r.reason}`} filters={[{ key: 'collection', label: 'Modules', options: [...new Set(permitted.map(e => e.collection))] }, { key: 'actorId', label: 'Actors', options: data.admins.filter(a => permitted.some(e => e.actorId === a.id)).map(a => ({ value: a.id, label: a.name })) }, { key: 'action', label: 'Actions', options: [...new Set(permitted.map(e => e.action))] }]} columns={[{ key: 'at', label: 'Time', sortable: true, render: r => <DateText value={r.at} full /> }, { key: 'subject', label: 'Subject', render: (r, from) => <Link to={`/audit/${r.id}`} state={from}>{r.subject}</Link> }, { key: 'action', label: 'Action', render: r => label(r.action) }, { key: 'actorName', label: 'Actor' }, { key: 'collection', label: 'Module' }, { key: 'result', label: 'Result', render: () => <Badge status="approved">Committed</Badge> }]} noun="decisions" /></Panel></>;
}
const roleOptions = Object.entries(ROLES).map(([value, label]) => ({ value, label }));
export function Settings({ section }) {
  const { data, actor, commit, theme, setTheme, density, setDensity } = useAdmin(); const [dialog, setDialog] = useState(null);
  const tabs = [{ id: 'general', name: 'General', cap: 'settings' }, { id: 'team', name: 'Team & access', cap: 'admins' }, { id: 'policies', name: 'Review policies', cap: 'settings' }, { id: 'preferences', name: 'Preferences', cap: 'preferences' }];
  const general = data.settings[0];
  return <><PageHeader title="Settings" description="Workspace configuration, platform access and personal preferences." /><nav className="tabs">{tabs.filter(t => can(actor, t.cap)).map(t => <NavLink key={t.id} className={({ isActive }) => isActive ? 'selected' : ''} to={`/settings/${t.id}`}>{t.name}</NavLink>)}</nav>
    {section === 'general' && <Panel title="Workspace identity" action={<Button onClick={() => setDialog({ action: 'general', row: general })}>Edit settings</Button>}><Descriptions items={[["Product name", general.name], ['Institution', general.institution], ['Support contact', <a href={`mailto:${general.supportEmail}`}>{general.supportEmail}</a>], ['Timezone', 'Asia/Dhaka (fixed)']]} /><div className="panel-body"><p className="muted">Name, institution and support contact are used by the admin shell. Public branding remains Ugrads.</p></div></Panel>}
    {section === 'team' && <><Note>Invitation delivery is simulated. Creating an invitation does not grant access. “Activate demo access” explicitly enables a local review session.</Note><Panel title="Platform administrators" action={<Button variant="primary" onClick={() => setDialog({ action: 'invite' })}><Plus size={16} />Invite administrator</Button>}><Register rows={data.admins} searchText={r => `${r.name} ${r.email || ''}`} defaultSort="name" columns={[{ key: 'name', label: 'Administrator', render: r => <><strong>{r.name}</strong><small className="block muted">{r.email || 'Seeded review account'}</small></> }, { key: 'role', label: 'Platform role', render: r => ROLES[r.role] }, { key: 'status', label: 'Access', render: r => <Badge status={r.status || (r.active ? 'active' : 'revoked')} /> }, { key: 'actions', label: 'Actions', render: r => <div className="actions"><Button disabled={r.id === actor.id} onClick={() => setDialog({ action: 'role', row: r })}>Change role</Button><Button disabled={r.id === actor.id} onClick={() => setDialog({ action: r.active ? 'revoke' : 'activate', row: r })}>{r.active ? 'Revoke' : 'Activate demo access'}</Button></div> }]} noun="administrators" /></Panel></>}
    {section === 'policies' && <Panel title="Current review policy" description="Release rules are fixed; these are not switches that enable unsupported behavior."><Descriptions items={[["Hiring & Seeking", 'Submitted posts require platform review. Drafts remain author-private.'], ['Department events', 'Publish directly through eligible department accounts.'], ['Moderation', 'Case-scoped submitted evidence; account restrictions are escalated.'], ['Stories', 'Disabled'], ['Photo Moments', '24-hour lifetime from original creation. No enduring media archive.'], ['Decision reasons', 'Required for restrictions, removals, rejection, cancellation and intervention.'], ['Notifications', 'Local decision outcomes only. No live email or push delivery.']]} /></Panel>}
    {section === 'preferences' && <Panel title="Your display preferences"><div className="analytics-filters"><Field label="Color theme">{p => <select {...p} value={theme} onChange={e => setTheme(e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select>}</Field><Field label="Register density">{p => <select {...p} value={density} onChange={e => setDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select>}</Field></div><div className="panel-body"><ShieldCheck size={18} /><p className="muted">Preferences are stored for this browser and only affect the admin dashboard.</p></div></Panel>}
    {dialog?.action === 'general' && <EditDialog title="Workspace identity" initial={dialog.row} fields={[{ key: 'name', label: 'Product name', required: true }, { key: 'institution', label: 'Institution', required: true }, { key: 'supportEmail', label: 'Support email', type: 'email', required: true }]} onClose={() => setDialog(null)} onSave={values => commit({ collection: 'settings', id: 'general', revision: dialog.row.revision, action: 'edit', values })} />}
    {['invite', 'role'].includes(dialog?.action) && <EditDialog title={dialog.action === 'invite' ? 'Draft invitation' : 'Change platform role'} initial={dialog.row || { role: 'operations' }} fields={[...(dialog.action === 'invite' ? [{ key: 'name', label: 'Full name', required: true }, { key: 'email', label: 'Email', type: 'email', required: true }] : []), { key: 'role', label: 'Platform role', options: roleOptions, required: true }, ...(dialog.action === 'role' ? [{ key: 'reason', label: 'Reason', type: 'textarea', required: true }] : [])]} onClose={() => setDialog(null)} onSave={values => commit({ collection: 'admins', id: dialog.row?.id || `admin-${crypto.randomUUID()}`, revision: dialog.row?.revision, action: dialog.action === 'invite' ? 'create' : 'role', values, reason: values.reason })} />}
    {['revoke', 'activate'].includes(dialog?.action) && <DecisionDialog title={dialog.action === 'revoke' ? 'Revoke access' : 'Activate demo access'} subject={dialog.row.name} destructive={dialog.action === 'revoke'} onClose={() => setDialog(null)} onSubmit={({ reason }) => commit({ collection: 'admins', id: dialog.row.id, revision: dialog.row.revision, action: dialog.action, reason })} />}
  </>;
}
