import { useState } from 'react';
import { Link, NavLink, useParams } from 'react-router-dom';
import { ArrowUpRight, Check } from 'lucide-react';
import { useAdmin } from '../app/context';
import { effectiveStatus, getById } from '../lib/model';
import { NotFound } from '../App';
import { BackLink, Badge, Button, DateText, DecisionDialog, Descriptions, History, Note, PageHeader, Panel, Person, Register } from '../components/ui';
function CareerTabs() { return <nav className="tabs" aria-label="Career workspaces"><NavLink to="/jobs/hiring">Hiring</NavLink><NavLink to="/jobs/seeking">Seeking work</NavLink></nav>; }
export function CareerList({ kind }) {
  const { data } = useAdmin(); const hiring = kind === 'hiring'; const rows = data[kind].map(r => ({ ...r, status: effectiveStatus(r, kind), author: getById(data, 'members', r.memberId)?.name, department: getById(data, 'members', r.memberId)?.department }));
  return <><PageHeader eyebrow="CAREER OPPORTUNITIES" title={hiring ? 'Hiring' : 'Seeking work'} description={hiring ? 'Review meaningful opportunities for the campus community.' : 'Connect verified student talent with their next opportunity.'} actions={<span className="count-chip">{rows.filter(r => r.status === 'pending').length} pending</span>} /><CareerTabs /><Panel><Register key={kind} rows={rows} defaultStatus="pending" noun="posts" searchLabel={hiring ? 'Search title, company or author…' : 'Search headline, student or skill…'} searchText={r => `${r.title} ${r.author} ${r.company || ''} ${r.skills.join(' ')}`} filters={[{ key: 'status', label: 'Statuses', options: hiring ? ['pending', 'published', 'rejected', 'changes_requested', 'closed', 'expired', 'removed'] : ['pending', 'active', 'paused', 'expired', 'rejected', 'changes_requested', 'removed'] }, { key: 'category', label: 'Categories', options: [...new Set(rows.map(r => r.category))] }, { key: 'department', label: 'Departments', options: [...new Set(rows.map(r => r.department))] }]} columns={[
    { key: 'title', label: hiring ? 'Opportunity' : 'Seeking post', sortable: true, render: (r, state) => <Link className="record-title" state={state} to={`/jobs/${kind}/${r.id}`}><strong>{r.title}</strong><small>{hiring ? r.company : r.skills.slice(0, 3).join(' · ')}</small></Link> },
    { key: 'author', label: hiring ? 'Posted by' : 'Student', sortable: true, render: r => <span className="cell-wrap">{r.author}<small className="muted">{r.department}</small></span> },
    { key: 'category', label: 'Category' }, { key: 'submittedAt', label: 'Submitted', sortable: true, render: r => <DateText value={r.submittedAt} full /> }, { key: 'status', label: 'Status', render: r => <Badge status={r.status} /> },
    { key: 'action', label: '', render: (r, state) => <Link state={state} className="text-link" to={`/jobs/${kind}/${r.id}`}>Review<ArrowUpRight size={14} /></Link> },
  ]} /></Panel></>;
}
export function CareerDetail({ kind }) {
  const { id } = useParams(); const { data, commit } = useAdmin(); const [decision, setDecision] = useState(null); const row = getById(data, kind, id); if (!row) return <NotFound />;
  const author = getById(data, 'members', row.memberId); const hiring = kind === 'hiring'; const status = effectiveStatus(row, kind); const eligible = author?.verified && author.status === 'active';
  const actions = status === 'pending' ? [{ id: 'approve', title: 'Approve post', primary: true }, { id: 'changes', title: 'Request changes' }, { id: 'reject', title: 'Reject post' }] : ['active', 'published', 'paused'].includes(status) ? [...(hiring ? [{ id: 'close', title: 'Close listing' }] : []), { id: 'remove', title: 'Remove post', destructive: true }] : [];
  const supporting = ['resumeUrl', 'portfolioUrl', 'linkedInUrl', 'githubUrl'].filter(key => row[key]);
  return <><BackLink to={`/jobs/${kind}`}>Back to {hiring ? 'hiring' : 'seeking work'}</BackLink><PageHeader eyebrow={`${hiring ? 'HIRING' : 'SEEKING'} / ${row.id}`} title={row.title} description={hiring ? `${row.company} · ${row.location}` : `${author.name} · ${row.category}`} actions={<Badge status={status} />} />
    <div className="detail-grid"><div className="form-stack"><Panel title={hiring ? 'Opportunity details' : 'Student introduction'}><div className="panel-body"><p className="body-copy">{row.description}</p><div className="skill-row">{row.skills.map(skill => <span key={skill}>{skill}</span>)}</div></div><Descriptions items={hiring ? [['Company', row.company], ['Category', row.category], ['Location', row.location], ['Compensation', row.compensation], ['Application deadline', <DateText value={row.deadline} full />], ['Application link', row.applicationUrl ? <a className="text-link" href={row.applicationUrl} target="_blank" rel="noreferrer">Open application<ArrowUpRight size={14} /></a> : 'Not supplied']] : [['Category', row.category], ['Work mode', row.workMode], ['Location', row.location], ['Availability', row.availability], ['Commitment', row.commitment], ['Preferred duration', row.preferredDuration], ['Compensation', row.compensation], ['Visibility', row.visibility], ['Post lifetime', `${row.durationDays} days`], ['Expires', <DateText value={row.expiresAt} full />]]} /></Panel>
    {!hiring && <Panel title="Supporting links"><div className="panel-body">{supporting.length ? supporting.map(key => <a key={key} className="entity-row" href={row[key]} target="_blank" rel="noreferrer">{({ resumeUrl: 'Resume', portfolioUrl: 'Portfolio', linkedInUrl: 'LinkedIn', githubUrl: 'GitHub' })[key]}<ArrowUpRight size={15} /></a>) : <p className="muted">No accessible supporting files or links were supplied with this submission.</p>}</div></Panel>}
    <Panel title="Decision history"><History entries={data.audit.filter(a => a.collection === kind && a.entityId === id)} /></Panel></div><aside className="form-stack"><Panel title="Submitted by"><div className="panel-body"><Link to={`/members/${author.id}`}><Person name={author.name} secondary={`${author.identity} · ${author.department}`} /></Link><div className="badge-row"><Badge status={author.status} /><Badge status={author.verified ? 'approved' : 'needs_information'}>{author.verified ? 'Verified' : 'Unverified'}</Badge></div><p className="help-text">Submitted <DateText value={row.submittedAt} full /></p></div></Panel><Panel title={actions.length ? 'Review this post' : 'Review outcome'}><div className="panel-body form-stack">{!eligible && status === 'pending' && <Note tone="warning">Verify or reactivate the author before approving this post.</Note>}{actions.length ? actions.map(a => <Button key={a.id} variant={a.primary ? 'primary' : 'secondary'} disabled={a.id === 'approve' && !eligible} onClick={() => setDecision({ ...a, revision: row.revision })}>{a.primary && <Check size={15} />}{a.title}</Button>) : <><Badge status={status} /><p>{row.reason || 'There are no available review actions in this state.'}</p></>}{!hiring && <p className="help-text">Approval does not renew an expired post or override a student’s pause or availability.</p>}</div></Panel></aside></div>
    {decision && <DecisionDialog title={decision.title} subject={row.title} destructive={decision.destructive} reasonRequired={decision.id !== 'approve'} onClose={() => setDecision(null)} onSubmit={({ reason }) => commit({ collection: kind, id, revision: decision.revision, action: decision.id, reason }, 'Career review saved.')} />}
  </>;
}
