import { useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Plus, Pencil, Archive, KeyRound } from 'lucide-react';
import { useAdmin } from '../app/context';
import { getById, can } from '../lib/model';
import { PERMISSIONS } from '../../../src/shared/departmentModel';
import { NotFound } from '../App';
import { BackLink, Badge, Button, ButtonLink, DecisionDialog, Descriptions, Empty, Field, History, Note, PageHeader, Panel, Person, Register, Tabs } from '../components/ui';
import EditDialog from '../components/ui/EditDialog';
const fields = [
  { key: 'name', label: 'Department name', required: true }, { key: 'code', label: 'Department code', required: true, maxLength: 24 },
  { key: 'school', label: 'School', required: true }, { key: 'description', label: 'About the department', type: 'textarea', maxLength: 2000 },
  { key: 'office', label: 'Office location' }, { key: 'hours', label: 'Office hours' }, { key: 'email', label: 'Contact email', type: 'email' },
  { key: 'phone', label: 'Phone / extension' }, { key: 'website', label: 'Website', type: 'url' },
  { key: 'cover', label: 'Cover image URL', type: 'url', hint: 'Use an https image URL. File storage will require a media service.' },
];
export function DepartmentList() {
  const { data } = useAdmin(); const claims = data.claims.filter(c => c.status === 'pending').length;
  return <><PageHeader eyebrow="COMMUNITY" title="Departments" description="Official campus hubs, their owners and delegated teams." actions={<><ButtonLink to="/departments/claims">Ownership claims<span className="count-chip">{claims}</span></ButtonLink><ButtonLink variant="primary" to="/departments/new"><Plus size={16} />Add department</ButtonLink></>} /><Panel><Register rows={data.departments} noun="departments" defaultSort="name" searchLabel="Search department or code…" searchText={r => `${r.name} ${r.code}`} filters={[{ key: 'school', label: 'Schools', options: [...new Set(data.departments.map(d => d.school))] }, { key: 'ownership', label: 'Ownership states', options: [{ value: 'owned', label: 'Owned' }, { value: 'unowned', label: 'Unowned' }], value: d => d.ownerId ? 'owned' : 'unowned' }, { key: 'status', label: 'Statuses', options: ['active', 'archived'] }]} columns={[
    { key: 'name', label: 'Department', sortable: true, render: (d, state) => <Link to={`/departments/${d.id}`} state={state}><Person square name={d.code} secondary={d.name} /></Link> },
    { key: 'school', label: 'School', render: d => <span className="cell-wrap">{d.school}</span> },
    { key: 'ownerId', label: 'Owner', render: d => d.ownerId ? getById(data, 'members', d.ownerId)?.name : <Badge status="needs_information">Unowned</Badge> },
    { key: 'team', label: 'Team', render: d => <span className="mono">{Object.keys(d.assignments).length} assigned</span> },
    { key: 'status', label: 'Status', render: d => <Badge status={d.status} /> }, { key: 'action', label: '', render: (d, state) => <Link state={state} className="row-link" to={`/departments/${d.id}`} aria-label={`Manage ${d.code}`}><ArrowUpRight size={16} /></Link> },
  ]} /></Panel></>;
}
export function DepartmentCreate() {
  const { commit } = useAdmin(); const navigate = useNavigate(); const [editing, setEditing] = useState(true);
  return <><BackLink to="/departments">All departments</BackLink><PageHeader title="Add department" description="Create an official hub. Ownership is reviewed separately." /><Panel><Empty title="New department" description="Add the department’s name, school and official contact information." action={<Button onClick={() => setEditing(true)}>Enter department details</Button>} /></Panel>{editing && <EditDialog title="Add department" fields={fields} onClose={() => { setEditing(false); navigate('/departments'); }} onSave={values => commit({ collection: 'departments', action: 'create', values }, 'Department created.')} />}</>;
}
export function DepartmentDetail() {
  const { id } = useParams(); const { data, actor, commit } = useAdmin(); const [params] = useSearchParams(); const [editing, setEditing] = useState(null); const [decision, setDecision] = useState(null); const [memberId, setMemberId] = useState(''); const [permission, setPermission] = useState('helpdesk');
  const row = getById(data, 'departments', id); if (!row) return <NotFound />;
  const requestedTab = params.get('tab'); const tab = ['overview', 'team', 'settings', 'activity'].includes(requestedTab) ? requestedTab : 'overview'; const owner = getById(data, 'members', row.ownerId);
  const openAction = (action, title, personId = '') => { setMemberId(personId); setPermission(row.assignments[personId] || 'helpdesk'); setDecision({ action, title, revision: row.revision }); };
  return <><BackLink to="/departments">All departments</BackLink><PageHeader eyebrow={`DEPARTMENT / ${row.code}`} title={row.name} description={row.school} actions={<><Badge status={row.status} />{row.status === 'active' && <a className="btn secondary" target="_blank" rel="noreferrer" href={`/webapp/departments/${row.id}`}>Public hub<ArrowUpRight size={15} /></a>}<Button onClick={() => setEditing({ ...row })}><Pencil size={15} />Edit page</Button></>} />
    <Tabs items={[{ id: 'overview', label: 'Overview' }, { id: 'team', label: 'Team & access' }, { id: 'settings', label: 'Page settings' }, { id: 'activity', label: 'Activity' }]} />
    {tab === 'overview' && <div className="detail-grid"><Panel title="Official identity"><div className="panel-body"><Person square name={row.code} secondary={row.name} /><p className="body-copy">{row.description || 'No description added yet.'}</p></div><Descriptions items={[[ 'Office', row.office ], ['Office hours', row.hours], ['Email', row.email], ['Phone', row.phone], ['Website', row.website ? <a className="text-link" href={row.website} target="_blank" rel="noreferrer">{row.website}<ArrowUpRight size={14} /></a> : null]]} /></Panel><div className="form-stack"><Panel title="Ownership"><div className="panel-body">{owner ? <Link to={`/members/${owner.id}`}><Person name={owner.name} secondary="Department owner" /></Link> : <><Badge status="needs_information">Unowned department</Badge><p className="muted">Review faculty ownership requests to appoint an owner.</p><ButtonLink to="/departments/claims">Review claims</ButtonLink></>}</div></Panel><Panel title="Team coverage"><div className="panel-body"><div className="metric-number">{Object.keys(row.assignments).length}</div><p className="muted">Delegated teammates</p><Link to="?tab=team" className="text-link">View team & access<ArrowUpRight size={14} /></Link></div></Panel><Note>Public hub metadata and access reflect local decisions on this origin. Private Help Desk threads remain in the department workspace.</Note></div></div>}
    {tab === 'team' && <><Note>Routine delegation belongs to the department owner. Platform interventions require a reason and are recorded.</Note><Panel title="Owner & delegated team" action={<Button disabled={row.status !== 'active'} onClick={() => openAction('access', 'Update department access')}><Plus size={15} />Assign teammate</Button>}>{owner && <div className="entity-row"><Person name={owner.name} secondary={owner.identity} /><Badge status="neutral">Department owner</Badge></div>}{Object.entries(row.assignments).map(([personId, p]) => <div key={personId} className="entity-row"><Link to={`/members/${personId}`}><Person name={getById(data, 'members', personId)?.name} secondary={getById(data, 'members', personId)?.identity} /></Link><span>{PERMISSIONS[p]?.label}</span><Button disabled={row.status !== 'active'} onClick={() => openAction('access', 'Update department access', personId)}>Manage</Button></div>)}{!owner && !Object.keys(row.assignments).length && <Empty title="No assigned team" description="Review ownership or assign a verified teammate." />}</Panel></>}
    {tab === 'settings' && <div className="form-stack"><Panel title="Page details" action={<Button onClick={() => setEditing({ ...row })}>Edit details</Button>}><Descriptions items={[[ 'Name', row.name ], ['Code', row.code], ['School', row.school], ['Description', row.description], ['Office', row.office], ['Hours', row.hours], ['Email', row.email], ['Phone', row.phone], ['Website', row.website], ['Cover image', row.cover || 'Not set']]} /></Panel><Panel title="Department lifecycle"><div className="entity-row"><div><strong>{row.status === 'active' ? 'Archive department' : 'Reactivate department'}</strong><small>Keep existing records and memberships. Archived hubs cannot publish new content.</small></div><Button onClick={() => openAction(row.status === 'active' ? 'archive' : 'reactivate', row.status === 'active' ? 'Archive department' : 'Reactivate department')}><Archive size={15} />{row.status === 'active' ? 'Archive' : 'Reactivate'}</Button></div>{can(actor, 'recovery') && <div className="entity-row"><div><strong>Recover ownership</strong><small>Appoint an active verified member. The previous owner becomes a Primary Admin.</small></div><Button disabled={row.status !== 'active'} onClick={() => openAction('recover', 'Recover ownership')}><KeyRound size={15} />Recover</Button></div>}</Panel></div>}
    {tab === 'activity' && <Panel title="Department activity"><History entries={data.audit.filter(a => a.collection === 'departments' && a.entityId === id || a.collection === 'claims' && data.claims.some(c => c.id === a.entityId && c.departmentId === id))} /></Panel>}
    {editing && <EditDialog title="Edit department page" fields={fields} initial={editing} onClose={() => setEditing(null)} onSave={values => commit({ collection: 'departments', id, revision: editing.revision, action: 'edit', values }, 'Department page updated.')} />}
    {decision && <DecisionDialog title={decision.title} subject={decision.action === 'recover' && memberId ? getById(data, 'members', memberId)?.name : row.code} destructive={['archive', 'recover'].includes(decision.action) || permission === 'remove' && decision.action === 'access'} onClose={() => setDecision(null)} onSubmit={({ reason }) => commit({ collection: 'departments', id, revision: decision.revision, action: decision.action, reason, values: { memberId, permission } }, 'Department updated.')}>
      {['access', 'recover'].includes(decision.action) && <div className="form-stack"><Field label={decision.action === 'recover' ? 'New owner' : 'Member'}>{props => <select {...props} required value={memberId} onChange={e => { setMemberId(e.target.value); setPermission(row.assignments[e.target.value] || 'helpdesk'); }}><option value="">Choose a verified member…</option>{data.members.filter(m => m.id !== row.ownerId && (m.verified && m.status === 'active' || decision.action === 'access' && row.assignments[m.id])).map(m => <option key={m.id} value={m.id}>{m.name} · {m.identity} · {m.department}</option>)}</select>}</Field>{decision.action === 'access' && <Field label="Permission">{props => <select {...props} value={permission} onChange={e => setPermission(e.target.value)}>{Object.entries(PERMISSIONS).map(([key, p]) => <option key={key} value={key}>{p.label}</option>)}{row.assignments[memberId] && <option value="remove">Remove access</option>}</select>}</Field>}</div>}
    </DecisionDialog>}
  </>;
}
