import { useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { Pencil, ShieldAlert, ArrowUpRight } from 'lucide-react';
import { useAdmin } from '../app/context';
import { getById, ROLES } from '../lib/model';
import { PERMISSIONS } from '../../../src/shared/departmentModel';
import { NotFound } from '../App';
import { BackLink, Badge, Button, DateText, DecisionDialog, Descriptions, Empty, History, PageHeader, Panel, Person, Register, Tabs } from '../components/ui';
import EditDialog from '../components/ui/EditDialog';

export function MemberList() {
  const { data } = useAdmin();
  return <><PageHeader eyebrow="COMMUNITY" title="Members" description="People, identities and access — all in one place." actions={<span className="count-chip">{data.members.length} members</span>} /><Panel><Register rows={data.members} noun="members" defaultSort="name" searchLabel="Search name, ID or email…" searchText={m => `${m.name} ${m.id} ${m.email}`} filters={[
    { key: 'identity', label: 'Identities', options: ['Student', 'Alumni', 'Faculty', 'Staff'] }, { key: 'department', label: 'Departments', options: [...new Set(data.members.map(m => m.department))] }, { key: 'verified', label: 'Verification states', options: [{ value: 'true', label: 'Verified' }, { value: 'false', label: 'Unverified' }] }, { key: 'status', label: 'Statuses', options: ['active', 'suspended'] },
  ]} columns={[
    { key: 'name', label: 'Member', sortable: true, render: (m, state) => <Link to={`/members/${m.id}`} state={state}><Person name={m.name} secondary={m.email} /></Link> },
    { key: 'identity', label: 'Identity', sortable: true }, { key: 'department', label: 'Affiliation', sortable: true },
    { key: 'verified', label: 'Verification', render: m => <Badge status={m.verified ? 'approved' : 'neutral'}>{m.verified ? 'Verified' : 'Unverified'}</Badge> },
    { key: 'status', label: 'Account', render: m => <Badge status={m.status} /> }, { key: 'joinedAt', label: 'Joined', sortable: true, render: m => <DateText value={m.joinedAt} /> },
    { key: 'action', label: '', render: (m, state) => <Link className="row-link" to={`/members/${m.id}`} state={state} aria-label={`View ${m.name}`}><ArrowUpRight size={16} /></Link> },
  ]} /></Panel></>;
}
export function MemberDetail() {
  const { id } = useParams(); const { data, commit } = useAdmin(); const [params] = useSearchParams(); const [action, setAction] = useState(null); const [editing, setEditing] = useState(null);
  const member = getById(data, 'members', id); if (!member) return <NotFound />;
  const requestedTab = params.get('tab'); const tab = ['profile', 'verification', 'access', 'activity'].includes(requestedTab) ? requestedTab : 'profile'; const requests = data.verification.filter(v => v.memberId === id); const platform = data.admins.find(a => a.memberId === id);
  return <><BackLink to="/members">All members</BackLink><PageHeader eyebrow={`MEMBER / ${id}`} title={member.name} description={`${member.identity} · ${member.department}`} actions={<><Badge status={member.status} /><Button onClick={() => setEditing({ ...member })}><Pencil size={15} />Edit profile</Button><Button onClick={() => setAction({ ...member })}><ShieldAlert size={15} />{member.status === 'active' ? 'Suspend account' : 'Reactivate account'}</Button></>} />
    <Tabs items={[{ id: 'profile', label: 'Profile' }, { id: 'verification', label: 'Verification' }, { id: 'access', label: 'Access' }, { id: 'activity', label: 'Activity' }]} />
    {tab === 'profile' && <div className="detail-grid"><Panel title="Profile information"><Descriptions items={[[ 'Full name', member.name ], ['Email', member.email], ['Academic identity', member.identity], ['Department / office', member.department], ['Designation', member.designation], ...(member.identity === 'Staff' ? [['Office location', member.office], ['Extension', member.phone]] : [['Batch', member.batch]]), ['Joined', <DateText value={member.joinedAt} full />]]} /></Panel><Panel title="Account overview"><div className="panel-body"><Person name={member.name} secondary={`Member ID ${member.id}`} /><div className="badge-row"><Badge status={member.status} /><Badge status={member.verified ? 'approved' : 'neutral'}>{member.verified ? 'Verified identity' : 'Identity unverified'}</Badge></div><p className="muted">Verification confirms identity. Department permissions and platform access are assigned separately.</p></div></Panel></div>}
    {tab === 'verification' && <Panel title="Verification requests">{requests.length ? requests.map(v => <Link key={v.id} className="entity-row" to={`/verification/${v.id}`}><div><strong>{v.method}</strong><small><DateText value={v.submittedAt} full /></small></div><Badge status={v.status} /><ArrowUpRight size={16} /></Link>) : <Empty title="No review requests" description={member.verified ? 'This member has a verified identity in the existing product fixture.' : 'No verification evidence has been submitted.'} />}</Panel>}
    {tab === 'access' && <div className="detail-grid"><Panel title="Department access">{data.departments.some(d => d.ownerId === id || d.assignments[id]) ? data.departments.filter(d => d.ownerId === id || d.assignments[id]).map(d => <Link key={d.id} className="entity-row" to={`/departments/${d.id}?tab=team`}><Person square name={d.code} secondary={d.name} /><span>{d.ownerId === id ? 'Department owner' : PERMISSIONS[d.assignments[id]]?.label}</span><ArrowUpRight size={16} /></Link>) : <Empty title="No department assignment" description="Academic identity alone does not grant department access." />}</Panel><Panel title="Platform access"><div className="panel-body"><Badge status={platform?.active ? 'active' : 'neutral'}>{platform ? `${ROLES[platform.role]}${platform.active ? '' : ' · Revoked'}` : 'No platform role'}</Badge><p className="muted">Platform roles are separate from member and department roles.</p></div></Panel></div>}
    {tab === 'activity' && <Panel title="Member activity"><History entries={data.audit.filter(a => a.collection === 'members' && a.entityId === id || requests.some(v => a.collection === 'verification' && a.entityId === v.id))} /><div className="panel-body"><h3>Authored career content</h3>{['hiring', 'seeking'].flatMap(kind => data[kind].filter(r => r.memberId === id).map(r => <Link className="entity-row" key={`${kind}-${r.id}`} to={`/jobs/${kind}/${r.id}`}><strong>{r.title}</strong><Badge status={r.status} /><ArrowUpRight size={16} /></Link>))}</div></Panel>}
    {action && <DecisionDialog title={action.status === 'active' ? 'Suspend account' : 'Reactivate account'} subject={member.name} destructive={action.status === 'active'} description="Account status changes preserve the profile and existing content. Department assignments are not deleted." onClose={() => setAction(null)} onSubmit={({ reason }) => commit({ collection: 'members', id, revision: action.revision, action: action.status === 'active' ? 'suspend' : 'reactivate', reason }, action.status === 'active' ? 'Account suspended.' : 'Account reactivated.')} />}
    {editing && <EditDialog title="Edit member profile" initial={editing} fields={[{ key: 'name', label: 'Full name', required: true }, { key: 'department', label: 'Department / office', required: true }, { key: 'designation', label: 'Designation' }, ...(member.identity === 'Staff' ? [{ key: 'office', label: 'Office location' }, { key: 'phone', label: 'Extension' }] : [])]} onClose={() => setEditing(null)} onSave={values => commit({ collection: 'members', id, revision: editing.revision, action: 'edit', values }, 'Profile updated.')} />}
  </>;
}
