import { Link } from 'react-router-dom';
import { HeartPulse, Flag, ArrowUpRight, BadgeCheck, Building2, BriefcaseBusiness, Users, ArrowRight, CheckCheck } from 'lucide-react';
import { useAdmin } from '../app/context';
import { can, queueItems } from '../lib/model';
import { Badge, DateText, Empty, History, PageHeader, Panel, Person } from '../components/ui';
const groups = [
  { key: 'requests', label: 'Emergency requests', short: 'Open requests', to: '/emergency/requests', icon: HeartPulse, text: 'Keep urgent campus requests current' },
  { key: 'moderation', label: 'Safety reports', short: 'Open cases', to: '/moderation', icon: Flag, text: 'Review reported community content' },
  { key: 'verification', label: 'Identity verification', short: 'Verifications', to: '/verification', icon: BadgeCheck, text: 'Confirm their place in the community' },
  { key: 'claims', label: 'Department ownership', short: 'Ownership claims', to: '/departments/claims', icon: Building2, text: 'Connect departments with their leaders' },
  { key: 'hiring', label: 'Hiring opportunities', short: 'Hiring posts', to: '/jobs/hiring', icon: BriefcaseBusiness, text: 'Review opportunities for your campus' },
  { key: 'seeking', label: 'Seeking work', short: 'Seeking posts', to: '/jobs/seeking', icon: Users, text: 'Help student talent get discovered' },
];
export default function Overview() {
  const { data, actor } = useAdmin(); const queue = queueItems(data); const operates = can(actor, 'members');
  return <><PageHeader eyebrow="YOUR CAMPUS, AT A GLANCE" title="Overview" description={operates ? 'A clear view of what needs your attention today.' : 'Your campus workspace at a glance.'} actions={<span className="date-label">{new Date().toLocaleDateString('en-GB', { timeZone: 'Asia/Dhaka', weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })}</span>} />
    <div className="metric-grid">{groups.map(g => { const permitted = can(actor, g.key); const content = <><div className="metric-label"><span>{g.short}</span><g.icon size={16} /></div><div className="metric-number">{actor.role === 'moderator' && !permitted ? '—' : queue.filter(q => q.collection === g.key && (actor.role !== 'moderator' || q.assigneeId === actor.id)).length}<span>{permitted ? <ArrowUpRight size={18} /> : null}</span></div><small>{actor.role === 'moderator' ? permitted ? 'Assigned to you' : 'Outside your review scope' : 'Awaiting review'}</small></>; return permitted ? <Link key={g.key} className="metric-card" to={g.to}>{content}</Link> : <div key={g.key} className="metric-card">{content}</div>; })}</div>
    {operates ? <div className="overview-grid"><div className="overview-main"><Panel title="Needs attention" description="Urgent requests and high-severity reports first, then oldest submissions." action={<span className="count-chip">{queue.length} pending</span>}>
      {queue.length ? <div className="attention-list">{queue.slice(0, 7).map(item => { const group = groups.find(g => g.key === item.collection); return <Link to={item.href} className="attention-row" key={`${item.collection}-${item.id}`}><span className="queue-icon"><group.icon size={18} /></span><span className="attention-copy"><strong>{item.title}</strong><small>{group.label} <span>·</span> <DateText value={item.submittedAt} full /></small></span><Badge status="pending">Review</Badge><ArrowUpRight size={16} /></Link>; })}</div> : <Empty title="You’re all caught up" description="New submissions will appear here when they need review." icon={CheckCheck} />}
      <div className="panel-bottom">Showing {Math.min(7, queue.length)} of {queue.length} pending requests <span>Review by queue below</span></div>
    </Panel><Panel title="Review queues" description="Pick a workspace to continue."><div className="queue-cards">{groups.map(g => <Link key={g.key} to={g.to}><g.icon size={19} /><strong>{g.label}</strong><p>{g.text}</p><span>{queue.filter(q => q.collection === g.key && (actor.role !== 'moderator' || q.assigneeId === actor.id)).length} pending<ArrowRight size={15} /></span></Link>)}</div></Panel></div>
    <aside className="overview-rail"><Panel title="Community snapshot"><div className="snapshot"><div><span>Members</span><strong>{data.members.length}</strong></div><div><span>Verified identities</span><strong>{data.members.filter(m => m.verified).length}</strong></div><div><span>Active departments</span><strong>{data.departments.filter(d => d.status === 'active').length}</strong></div></div><div className="ownership-summary"><span>Department ownership</span><strong>{data.departments.filter(d => d.ownerId).length} of {data.departments.length} assigned</strong><div className="progress-track"><span style={{ width: `${data.departments.filter(d => d.ownerId).length / Math.max(1, data.departments.length) * 100}%` }} /></div><Link to="/departments?ownership=unowned">Review unowned departments<ArrowUpRight size={14} /></Link></div></Panel>
    <Panel title="Recent decisions"><History entries={data.audit.slice(0, 4)} /></Panel><div className="operator-note"><Person name={actor.name} secondary="Your decisions build a trusted community." /></div></aside></div> : <Panel title={actor.role === 'analyst' ? 'Community snapshot' : 'Your review scope'}><div className="panel-body"><p>{actor.role === 'analyst' ? `${data.members.length} members across ${data.departments.length} department hubs. Explore Analytics for period and department reporting.` : 'Open Moderation to review submitted evidence and resolve reports. Your audit log shows your cases and decisions.'}</p></div></Panel>}
  </>;
}
